### ISSUE TITLE
Weird AttributeError exceptions in terminal output

### ISSUE THREAD

**Issue by ryandeering** [you-will-love-each-other/health-bot#15]
I'm noticing these weird exceptions happening in the output of the bot. Why does this happen? I'll have a look into it later. Might not be THAT harmful but no exceptions is a good amount of exceptions.

<pre>[ps621695]$ python3 bot.py&amp;
[1] 9040
[ps621695]$ HEALTHbot is online
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command &quot;leaderboard&quot; is not found
Ignoring exception in on_message_delete
Traceback (most recent call last):
  File &quot;/home/hackermans/.local/lib/python3.5/site-packages/discord/client.py&quot;, line 343, in _run_event
    await coro(*args, **kwargs)
  File &quot;bot.py&quot;, line 486, in on_message_delete
    await bot.get_channel(735169441729478717).send(embed= embed)
AttributeError: &apos;NoneType&apos; object has no attribute &apos;send&apos;
Ignoring exception in on_message_edit
Traceback (most recent call last):
  File &quot;/home/hackermans/.local/lib/python3.5/site-packages/discord/client.py&quot;, line 343, in _run_event
    await coro(*args, **kwargs)
  File &quot;bot.py&quot;, line 472, in on_message_edit
    await bot.get_channel(735169441729478717).send(embed= embed)
AttributeError: &apos;NoneType&apos; object has no attribute &apos;send&apos;
Ignoring exception in on_message_edit
Traceback (most recent call last):
  File &quot;/home/hackermans/.local/lib/python3.5/site-packages/discord/client.py&quot;, line 343, in _run_event
    await coro(*args, **kwargs)
  File &quot;bot.py&quot;, line 472, in on_message_edit
    await bot.get_channel(735169441729478717).send(embed= embed)
AttributeError: &apos;NoneType&apos; object has no attribute &apos;send&apos;
Ignoring exception in on_message_delete
Traceback (most recent call last):
  File &quot;/home/hackermans/.local/lib/python3.5/site-packages/discord/client.py&quot;, line 343, in _run_event
    await coro(*args, **kwargs)
  File &quot;bot.py&quot;, line 486, in on_message_delete
    await bot.get_channel(735169441729478717).send(embed= embed)
AttributeError: &apos;NoneType&apos; object has no attribute &apos;send&apos;
Ignoring exception in on_reaction_add
Traceback (most recent call last):
  File &quot;/home/hackermans/.local/lib/python3.5/site-packages/discord/client.py&quot;, line 343, in _run_event
    await coro(*args, **kwargs)
  File &quot;bot.py&quot;, line 552, in on_reaction_add
    if (reaction.emoji.name == &quot;cacostar&quot; or reaction.emoji.name == &quot;russtar&quot;) and reaction.count == 5:
AttributeError: &apos;str&apos; object has no attribute &apos;name&apos;
Ignoring exception in on_reaction_add
Traceback (most recent call last):
  File &quot;/home/hackermans/.local/lib/python3.5/site-packages/discord/client.py&quot;, line 343, in _run_event
    await coro(*args, **kwargs)
  File &quot;bot.py&quot;, line 552, in on_reaction_add
    if (reaction.emoji.name == &quot;cacostar&quot; or reaction.emoji.name == &quot;russtar&quot;) and reaction.count == 5:
AttributeError: &apos;str&apos; object has no attribute &apos;name&apos;
Ignoring exception in on_message_delete
Traceback (most recent call last):
  File &quot;/home/hackermans/.local/lib/python3.5/site-packages/discord/client.py&quot;, line 343, in _run_event
    await coro(*args, **kwargs)
  File &quot;bot.py&quot;, line 486, in on_message_delete
    await bot.get_channel(735169441729478717).send(embed= embed)
AttributeError: &apos;NoneType&apos; object has no attribute &apos;send&apos;
Ignoring exception in on_message_edit
Traceback (most recent call last):
  File &quot;/home/hackermans/.local/lib/python3.5/site-packages/discord/client.py&quot;, line 343, in _run_event
    await coro(*args, **kwargs)
  File &quot;bot.py&quot;, line 472, in on_message_edit
    await bot.get_channel(735169441729478717).send(embed= embed)
AttributeError: &apos;NoneType&apos; object has no attribute &apos;send&apos;
Ignoring exception in on_reaction_add
Traceback (most recent call last):
  File &quot;/home/hackermans/.local/lib/python3.5/site-packages/discord/client.py&quot;, line 343, in _run_event
    await coro(*args, **kwargs)
  File &quot;bot.py&quot;, line 552, in on_reaction_add
    if (reaction.emoji.name == &quot;cacostar&quot; or reaction.emoji.name == &quot;russtar&quot;) and reaction.count == 5:
AttributeError: &apos;str&apos; object has no attribute &apos;name&apos;
Ignoring exception in on_reaction_add
Traceback (most recent call last):
  File &quot;/home/hackermans/.local/lib/python3.5/site-packages/discord/client.py&quot;, line 343, in _run_event
    await coro(*args, **kwargs)
  File &quot;bot.py&quot;, line 552, in on_reaction_add
    if (reaction.emoji.name == &quot;cacostar&quot; or reaction.emoji.name == &quot;russtar&quot;) and reaction.count == 5:
AttributeError: &apos;str&apos; object has no attribute &apos;name&apos;
Ignoring exception in on_reaction_add
Traceback (most recent call last):
  File &quot;/home/hackermans/.local/lib/python3.5/site-packages/discord/client.py&quot;, line 343, in _run_event
    await coro(*args, **kwargs)
  File &quot;bot.py&quot;, line 552, in on_reaction_add
    if (reaction.emoji.name == &quot;cacostar&quot; or reaction.emoji.name == &quot;russtar&quot;) and reaction.count == 5:
AttributeError: &apos;str&apos; object has no attribute &apos;name&apos;
Ignoring exception in on_reaction_add
Traceback (most recent call last):
  File &quot;/home/hackermans/.local/lib/python3.5/site-packages/discord/client.py&quot;, line 343, in _run_event
    await coro(*args, **kwargs)
  File &quot;bot.py&quot;, line 552, in on_reaction_add
    if (reaction.emoji.name == &quot;cacostar&quot; or reaction.emoji.name == &quot;russtar&quot;) and reaction.count == 5:
AttributeError: &apos;str&apos; object has no attribute &apos;name&apos;
Ignoring exception in on_reaction_add
Traceback (most recent call last):
  File &quot;/home/hackermans/.local/lib/python3.5/site-packages/discord/client.py&quot;, line 343, in _run_event
    await coro(*args, **kwargs)
  File &quot;bot.py&quot;, line 552, in on_reaction_add
    if (reaction.emoji.name == &quot;cacostar&quot; or reaction.emoji.name == &quot;russtar&quot;) and reaction.count == 5:
AttributeError: &apos;str&apos; object has no attribute &apos;name&apos;
Ignoring exception in on_reaction_add
Traceback (most recent call last):
  File &quot;/home/hackermans/.local/lib/python3.5/site-packages/discord/client.py&quot;, line 343, in _run_event
    await coro(*args, **kwargs)
  File &quot;bot.py&quot;, line 552, in on_reaction_add
    if (reaction.emoji.name == &quot;cacostar&quot; or reaction.emoji.name == &quot;russtar&quot;) and reaction.count == 5:
AttributeError: &apos;str&apos; object has no attribute &apos;name&apos;
Ignoring exception in on_message_delete
Traceback (most recent call last):
  File &quot;/home/hackermans/.local/lib/python3.5/site-packages/discord/client.py&quot;, line 343, in _run_event
    await coro(*args, **kwargs)
  File &quot;bot.py&quot;, line 486, in on_message_delete
    await bot.get_channel(735169441729478717).send(embed= embed)
AttributeError: &apos;NoneType&apos; object has no attribute &apos;send&apos;
Ignoring exception in on_message_edit
Traceback (most recent call last):
  File &quot;/home/hackermans/.local/lib/python3.5/site-packages/discord/client.py&quot;, line 343, in _run_event
    await coro(*args, **kwargs)
  File &quot;bot.py&quot;, line 472, in on_message_edit
    await bot.get_channel(735169441729478717).send(embed= embed)
AttributeError: &apos;NoneType&apos; object has no attribute &apos;send&apos;
Ignoring exception in on_message_edit
Traceback (most recent call last):
  File &quot;/home/hackermans/.local/lib/python3.5/site-packages/discord/client.py&quot;, line 343, in _run_event
    await coro(*args, **kwargs)
  File &quot;bot.py&quot;, line 472, in on_message_edit
    await bot.get_channel(735169441729478717).send(embed= embed)
AttributeError: &apos;NoneType&apos; object has no attribute &apos;send&apos;
Ignoring exception in on_reaction_add
Traceback (most recent call last):
  File &quot;/home/hackermans/.local/lib/python3.5/site-packages/discord/client.py&quot;, line 343, in _run_event
    await coro(*args, **kwargs)
  File &quot;bot.py&quot;, line 552, in on_reaction_add
    if (reaction.emoji.name == &quot;cacostar&quot; or reaction.emoji.name == &quot;russtar&quot;) and reaction.count == 5:
AttributeError: &apos;str&apos; object has no attribute &apos;name&apos;
Ignoring exception in on_message_edit
Traceback (most recent call last):
  File &quot;/home/hackermans/.local/lib/python3.5/site-packages/discord/client.py&quot;, line 343, in _run_event
    await coro(*args, **kwargs)
  File &quot;bot.py&quot;, line 472, in on_message_edit
    await bot.get_channel(735169441729478717).send(embed= embed)
AttributeError: &apos;NoneType&apos; object has no attribute &apos;send&apos;
[ps621695]$ Ignoring exception in on_message_edit
Traceback (most recent call last):
  File &quot;/home/hackermans/.local/lib/python3.5/site-packages/discord/client.py&quot;, line 343, in _run_event
    await coro(*args, **kwargs)
  File &quot;bot.py&quot;, line 472, in on_message_edit
    await bot.get_channel(735169441729478717).send(embed= embed)
AttributeError: &apos;NoneType&apos; object has no attribute &apos;send&apos;

</pre>

**Comment by slocknad** [comment]
I know why all of these attribute errors happen. Some are due to the ``big-brother-is-watching`` channel ID being incorrect, the others are located in ``on_reaction_add`` and happen because a default discord emoji is used for a reaction. Default emojis are received as a string so they don't have attributes like name or ID. So it should be really easy to fix and none of them is harmful at all so that's good. I'll fix it today, I guess
