### ISSUE TITLE
datetime variable used when users leave is incorrect

### ISSUE THREAD

**Issue by slocknad** [you-will-love-each-other/health-bot#21]
When users leave the server, mods will often come across messages like "[user.mention] joined -1 days, 17 hours, 37 seconds ago". For some unknown reason, discord provides the joined_at member attribute variable 24 hours before the real time they joined. I had already noticed this before

**Comment by martin-sweeny** [comment]
Example here:
https://discord.com/channels/688206199992483851/733746271684263936/880888951924207658

**Comment by martin-sweeny** [comment]
https://discordpy.readthedocs.io/en/stable/api.html#discord.Member.joined_at
Discord.py returns the date in UTC, we should use `datetime.utcnow()` to ensure the correct timezone is used for comparison
