### ISSUE TITLE
We need set up documentation

### ISSUE THREAD

**Issue by martin-sweeny** [you-will-love-each-other/health-bot#7]
There are at least two dependencies with no indication about how to configure them, and no documentation about set up

**Comment by ryandeering** [comment]
What format is preferable? The Github wiki?

**Comment by slocknad** [comment]
> What format is preferable? The Github wiki?

I think it is compact enough for the readme file. I will write it in a couple of days

**Comment by martin-sweeny** [comment]
I forgot to close this but I wrote docs here:
https://github.com/you-will-love-each-other/health-bot/wiki/Development-Environment-Setup
